INSERT INTO region (id_region, nombre) VALUES (1, 'Arica y Parinacota');
INSERT INTO region (id_region, nombre) VALUES (2, 'Tarapacá');
INSERT INTO region (id_region, nombre) VALUES (3, 'Antofagasta');
INSERT INTO region (id_region, nombre) VALUES (4, 'Atacama');
INSERT INTO region (id_region, nombre) VALUES (5, 'Coquimbo');
INSERT INTO region (id_region, nombre) VALUES (6, 'Valparaíso');
INSERT INTO region (id_region, nombre) VALUES (7, 'Región Metropolitana de Santiago');
INSERT INTO region (id_region, nombre) VALUES (8, "Libertador General Bernardo O'Higgins");
INSERT INTO region (id_region, nombre) VALUES (9, 'Maule');
INSERT INTO region (id_region, nombre) VALUES (10, 'Ñuble');
INSERT INTO region (id_region, nombre) VALUES (11, 'Biobío');
INSERT INTO region (id_region, nombre) VALUES (12, 'La Araucanía');
INSERT INTO region (id_region, nombre) VALUES (13, 'Los Ríos');
INSERT INTO region (id_region, nombre) VALUES (14, 'Los Lagos');
INSERT INTO region (id_region, nombre) VALUES (15, 'Aysén');
INSERT INTO region (id_region, nombre) VALUES (16, 'Magallanes');
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (1, 'Arica', 1);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (2, 'Camarones', 1);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (3, 'Putre', 1);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (4, 'General Lagos', 1);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (5, 'Iquique', 2);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (6, 'Alto Hospicio', 2);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (7, 'Pozo Almonte', 2);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (8, 'Huara', 2);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (9, 'Camiña', 2);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (10, 'Colchane', 2);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (11, 'Pica', 2);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (12, 'Antofagasta', 3);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (13, 'Mejillones', 3);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (14, 'Sierra Gorda', 3);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (15, 'Taltal', 3);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (16, 'Calama', 3);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (17, 'Ollagúe', 3);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (18, 'San Pedro de Atacama', 3);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (19, 'Tocopilla', 3);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (20, 'María Elena', 3);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (21, 'Copiapó', 4);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (22, 'Caldera', 4);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (23, 'Tierra Amarilla', 4);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (24, 'Chañaral', 4);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (25, 'Diego de Almagro', 4);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (26, 'Vallenar', 4);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (27, 'Huasco', 4);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (28, 'Freirina', 4);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (29, 'Alto del Carmen', 4);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (30, 'La Serena', 5);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (31, 'Coquimbo', 5);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (32, 'Andacollo', 5);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (33, 'La Higuera', 5);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (34, 'Vicuña', 5);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (35, 'Paihuano', 5);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (36, 'Ovalle', 5);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (37, 'Monte Patria', 5);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (38, 'Combarbalá', 5);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (39, 'Punitaqui', 5);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (40, 'Río Hurtado', 5);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (41, 'Illapel', 5);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (42, 'Salamanca', 5);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (43, 'Los Vilos', 5);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (44, 'Canela', 5);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (45, 'Valparaíso', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (46, 'Viña del Mar', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (47, 'Concón', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (48, 'Quintero', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (49, 'Puchuncaví', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (50, 'Quilpué', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (51, 'Villa Alemana', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (52, 'Limache', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (53, 'Olmué', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (54, 'San Antonio', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (55, 'Cartagena', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (56, 'El Tabo', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (57, 'El Quisco', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (58, 'Algarrobo', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (59, 'Santo Domingo', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (60, 'Casablanca', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (61, 'San Felipe', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (62, 'Putaendo', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (63, 'Santa María', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (64, 'Catemu', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (65, 'Panquehue', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (66, 'Llaillay', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (67, 'Los Andes', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (68, 'Calle Larga', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (69, 'Rinconada', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (70, 'San Esteban', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (71, 'La Ligua', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (72, 'Cabildo', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (73, 'Zapallar', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (74, 'Papudo', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (75, 'Petorca', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (76, 'Isla de Pascua', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (77, 'Juan Fernández', 6);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (78, 'Santiago', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (79, 'Providencia', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (80, 'Ñuñoa', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (81, 'Las Condes', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (82, 'Vitacura', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (83, 'La Reina', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (84, 'Peñalolén', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (85, 'Macul', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (86, 'San Joaquín', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (87, 'La Florida', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (88, 'Puente Alto', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (89, 'San José de Maipo', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (90, 'Pirque', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (91, 'Maipú', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (92, 'Cerrillos', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (93, 'Estación Central', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (94, 'Lo Prado', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (95, 'Pudahuel', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (96, 'Cerro Navia', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (97, 'Quinta Normal', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (98, 'Lo Espejo', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (99, 'Pedro Aguirre Cerda', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (100, 'San Miguel', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (101, 'San Joaquín', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (102, 'La Granja', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (103, 'El Bosque', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (104, 'La Cisterna', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (105, 'San Ramón', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (106, 'La Pintana', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (107, 'Huechuraba', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (108, 'Recoleta', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (109, 'Independencia', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (110, 'Renca', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (111, 'Conchalí', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (112, 'Quilicura', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (113, 'Lo Barnechea', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (114, 'Tiltil', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (115, 'Colina', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (116, 'Lampa', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (117, 'Melipilla', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (118, 'Curacaví', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (119, 'María Pinto', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (120, 'San Pedro', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (121, 'Alhué', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (122, 'Talagante', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (123, 'Peñaflor', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (124, 'Padre Hurtado', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (125, 'Isla de Maipo', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (126, 'El Monte', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (127, 'Buin', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (128, 'Paine', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (129, 'Calera de Tango', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (130, 'San Bernardo', 7);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (131, 'Rancagua', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (132, 'Machalí', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (133, 'Graneros', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (134, 'Mostazal', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (135, 'Codegua', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (136, 'Requínoa', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (137, 'Rengo', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (138, 'Malloa', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (139, 'Quinta de Tilcoco', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (140, 'San Vicente', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (141, 'Peumo', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (142, 'Pichidegua', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (143, 'Las Cabras', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (144, 'Coltauco', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (145, 'Doñihue', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (146, 'Coinco', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (147, 'Olivar', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (148, 'Gultro', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (149, 'San Fernando', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (150, 'Chimbarongo', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (151, 'Nancagua', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (152, 'Placilla', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (153, 'Santa Cruz', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (154, 'Palmilla', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (155, 'Peralillo', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (156, 'Pumanque', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (157, 'Lolol', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (158, 'Marchigúe', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (159, 'Paredones', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (160, 'Pichilemu', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (161, 'La Estrella', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (162, 'Litueche', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (163, 'Navidad', 8);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (164, 'Talca', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (165, 'San Clemente', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (166, 'Pelarco', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (167, 'Pencahue', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (168, 'Maule', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (169, 'San Rafael', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (170, 'Curepto', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (171, 'Constitución', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (172, 'Empedrado', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (173, 'Río Claro', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (174, 'Linares', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (175, 'Yerbas Buenas', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (176, 'Colbún', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (177, 'Longaví', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (178, 'Retiro', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (179, 'Parral', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (180, 'Villa Alegre', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (181, 'San Javier', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (182, 'Cauquenes', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (183, 'Chanco', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (184, 'Pelluhue', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (185, 'Curicó', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (186, 'Teno', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (187, 'Romeral', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (188, 'Sagrada Familia', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (189, 'Molina', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (190, 'Rauco', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (191, 'Hualañé', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (192, 'Licantén', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (193, 'Vichuquén', 9);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (194, 'Chillán', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (195, 'Chillán Viejo', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (196, 'Bulnes', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (197, 'Quillón', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (198, 'San Ignacio', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (199, 'El Carmen', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (200, 'Pemuco', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (201, 'Yungay', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (202, 'San Carlos', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (203, 'San Nicolás', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (204, 'Ñiquén', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (205, 'Coihueco', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (206, 'San Fabián', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (207, 'Quirihue', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (208, 'Cobquecura', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (209, 'Ninhue', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (210, 'Portezuelo', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (211, 'Ránquil', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (212, 'Coelemu', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (213, 'Treguaco', 10);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (214, 'Concepción', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (215, 'Talcahuano', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (216, 'Hualpén', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (217, 'Chiguayante', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (218, 'San Pedro de la Paz', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (219, 'Coronel', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (220, 'Lota', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (221, 'Penco', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (222, 'Tomé', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (223, 'Hualqui', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (224, 'Florida', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (225, 'Santa Juana', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (226, 'Los Ãngeles', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (227, 'Mulchén', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (228, 'Nacimiento', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (229, 'Negrete', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (230, 'Santa Bárbara', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (231, 'Quilaco', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (232, 'Quilleco', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (233, 'Cabrero', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (234, 'Yumbel', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (235, 'Laja', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (236, 'San Rosendo', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (237, 'Tucapel', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (238, 'Antuco', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (239, 'Alto Biobío', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (240, 'Arauco', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (241, 'Cañete', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (242, 'Contulmo', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (243, 'Curanilahue', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (244, 'Lebu', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (245, 'Los Ãlamos', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (246, 'Tirúa', 11);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (247, 'Temuco', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (248, 'Padre Las Casas', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (249, 'Lautaro', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (250, 'Vilcún', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (251, 'Perquenco', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (252, 'Galvarino', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (253, 'Cholchol', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (254, 'Nueva Imperial', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (255, 'Carahue', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (256, 'Saavedra', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (257, 'Teodoro Schmidt', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (258, 'Toltén', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (259, 'Freire', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (260, 'Pitrufquén', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (261, 'Gorbea', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (262, 'Loncoche', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (263, 'Villarrica', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (264, 'Pucón', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (265, 'Curarrehue', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (266, 'Melipeuco', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (267, 'Cunco', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (268, 'Curacautín', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (269, 'Lonquimay', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (270, 'Victoria', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (271, 'Traiguén', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (272, 'Los Sauces', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (273, 'Purén', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (274, 'Angol', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (275, 'Renaico', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (276, 'Collipulli', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (277, 'Ercilla', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (278, 'Lumaco', 12);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (279, 'Valdivia', 13);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (280, 'Corral', 13);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (281, 'Lanco', 13);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (282, 'Máfil', 13);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (283, 'Mariquina', 13);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (284, 'Panguipulli', 13);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (285, 'Los Lagos', 13);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (286, 'Paillaco', 13);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (287, 'La Unión', 13);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (288, 'Río Bueno', 13);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (289, 'Futrono', 13);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (290, 'Lago Ranco', 13);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (291, 'Puerto Montt', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (292, 'Puerto Varas', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (293, 'Llanquihue', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (294, 'Frutillar', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (295, 'Fresia', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (296, 'Los Muermos', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (297, 'Maullín', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (298, 'Calbuco', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (299, 'Cochamó', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (300, 'Ancud', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (301, 'Castro', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (302, 'Chonchi', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (303, 'Curaco de Vélez', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (304, 'Dalcahue', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (305, 'Puqueldón', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (306, 'Queilén', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (307, 'Quellón', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (308, 'Quemchi', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (309, 'Quinchao', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (310, 'Osorno', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (311, 'San Juan de la Costa', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (312, 'San Pablo', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (313, 'Purranque', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (314, 'Río Negro', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (315, 'Puyehue', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (316, 'Puyuhuapi', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (317, 'Hualaihué', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (318, 'Chaitén', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (319, 'Futaleufú', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (320, 'Palena', 14);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (321, 'Coyhaique', 15);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (322, 'Aysén', 15);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (323, 'Cisnes', 15);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (324, 'Guaitecas', 15);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (325, 'Río Ibáñez', 15);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (326, 'Chile Chico', 15);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (327, 'Cochrane', 15);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (328, "O'Higgins", 15);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (329, 'Tortel', 15);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (330, 'Lago Verde', 15);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (331, 'Punta Arenas', 16);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (332, 'Puerto Natales', 16);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (333, 'Porvenir', 16);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (334, 'Puerto Williams', 16);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (335, 'Laguna Blanca', 16);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (336, 'Río Verde', 16);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (337, 'San Gregorio', 16);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (338, 'Torres del Paine', 16);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (339, 'Primavera', 16);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (340, 'Timaukel', 16);
INSERT INTO comuna (id_comuna, nombre, id_region) VALUES (341, 'Cabo de Hornos', 16);



-- Poblar la tabla tipo_usuario con perfiles del sistema
INSERT INTO tipo_usuario (id_tipo_usuario, nombre) VALUES
(1, 'Administrador del Sistema'),
(2, 'Gestor de Inventario'),
(3, 'Encargado de Logística'),
(4, 'Jefe de Producción o Manufactura'),
(5, 'Auditor de Inventario'),
(6, 'Gerente de Proyectos'),
(7, 'Trabajador de Planta');
